### ISSUE TITLE
S3 object prefix

### ISSUE THREAD

**Issue by jwestbrook** [mewa/s3abird#1]
Add a setting option to only crawl a specific S3 prefix instead of crawling the whole S3 bucket.

**Comment by mewa** [comment]
That's a valid use-case. PR #2 adds a short term solution for this.

To specify a prefix simply append it to bucket name after slash, e.g. filing in `example/prefx` as S3 bucket will cause the app to list only keys from bucket `example` with prefix `prefx`.

In the long run it would probably be good to define a sidebar menu which allows to select prefixes.
